# Generated by Django 3.2.9 on 2021-11-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_card_deck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='owner',
            new_name='user',
        ),
    ]
